name: ownTest

on: 
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start Docker
      run: docker compose up -d --build
    - name: Enter Docker App Container
      run: docker exec turbofate_app /bin/sh
    - name: Prepare files
      run: npm ci
    - name: Prepare files 2
      run: npm install
    - name: Run tests
      run: node --test
    - name: Cleanup
      run: docker compose down
    
